DMLCatalog/DMLCatalog/Models/dmlcatalog.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMLCatalog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dmlcatalog
    {
        public int id { get; set; }
        public string name { get; set; }
        public string guid { get; set; }
        public string version { get; set; }
        public string description { get; set; }
        public int stateid { get; set; }
        public int typeid { get; set; }
        public Nullable<int> publisherid { get; set; }
        public Nullable<int> localizeid { get; set; }
        public string path { get; set; }
        public bool locked { get; set; }
    
        public virtual dmllocalize dmllocalize { get; set; }
        public virtual dmlpublisher dmlpublisher { get; set; }
        public virtual dmlstate dmlstate { get; set; }
        public virtual dmltype dmltype { get; set; }
    }
}

DMLCatalog/DMLCatalog/Controllers/dmlcatalogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.DirectoryServices;
using System.DirectoryServices.AccountManagement;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using DMLCatalog.Models;


namespace DMLCatalog.Controllers
{
    public class dmlcatalogsController : Controller
    {
        private dmldbEntities db = new dmldbEntities();
        
        // GET: dmlcatalogs
        public ActionResult Index(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id > 0)
            {
                var name =
                        (from c in db.dmlcatalog
                         where c.typeid == id
                         select c);

                return View(name.ToList());
            }
            var dmlcatalogs = db.dmlcatalog.Include(d => d.dmllocalize).Include(d => d.dmlpublisher).Include(d => d.dmlstate).Include(d => d.dmltype);
            
            return View(dmlcatalogs.ToList());
        }

        // GET: dmlcatalogs/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlcatalog dmlcatalog = db.dmlcatalog.Find(id);
            if (dmlcatalog == null)
            {
                return HttpNotFound();
            }
            return View(dmlcatalog);
        }

        // GET: dmlcatalogs/Create
        public ActionResult Create()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmlcatalog dm = new dmlcatalog();
            var id =
                        (from c in db.dmlcatalog
                         select c.id).ToArray().LastOrDefault();
            dm.id = id + 1;
            Guid g;
            g = Guid.NewGuid();
            dm.guid = g.ToString();
            ViewBag.localizeid = new SelectList(db.dmllocalize, "id", "name");
            ViewBag.publisherid = new SelectList(db.dmlpublisher, "id", "name");
            ViewBag.stateid = new SelectList(db.dmlstate, "id", "name");
            ViewBag.typeid = new SelectList(db.dmltype, "id", "name");
            
            return View(dm);
        }

        [HttpGet]
        public ActionResult Search(string search)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmlcatalog dm = new dmlcatalog();
            if (search != "")
            { 
            
            var name =
                        (from c in db.dmlcatalog
                         where c.name == search
                         select c);

            return View("Index", name.ToList());
            }
            else
            {
                return RedirectToAction("Index");
            }
        }


        [HttpGet]
        public ActionResult Upload()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            return View();
        }

        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase upload)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            try {
            dmlcatalog dm = new dmlcatalog();
            if (upload != null)
            {
                // получаем имя файла
                FileAttributes attributes = System.IO.File.GetAttributes(upload.FileName);
                // сохраняем файл в папку Files в проекте
                FileVersionInfo myFileVersionInfo = FileVersionInfo.GetVersionInfo(upload.FileName);
                
                dm.name = myFileVersionInfo.ProductName;
                dm.version = myFileVersionInfo.ProductVersion;
                dm.description = myFileVersionInfo.FileDescription;

                ViewBag.localizeid = new SelectList(db.dmllocalize, "id", "name");
                ViewBag.publisherid = new SelectList(db.dmlpublisher, "id", "name");
                ViewBag.stateid = new SelectList(db.dmlstate, "id", "name");
                ViewBag.typeid = new SelectList(db.dmltype, "id", "name");

                var id =
            (from c in db.dmlcatalog
             select c.id).ToArray().LastOrDefault();
                dm.id = id + 1;
                Guid g;
                g = Guid.NewGuid();
                dm.guid = g.ToString();
                ViewBag.path = (upload.FileName).Remove(upload.FileName.LastIndexOf('\\'));
            }
            return View("Create", dm);
            }
            catch(Exception ex)
            {
                ServiceReference1.DMLServiceClient dml = new ServiceReference1.DMLServiceClient();
                dml.Error(ex.Message);
                return View("Create");
            }
        }


        // POST: dmlcatalogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,guid,version,description,stateid,typeid,publisherid,localizeid")] dmlcatalog dmlcatalog)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            string target = @"\\market-200-040\DML\" + dmlcatalog.guid;
            if (ModelState.IsValid)
            {
                try
                {
                    ServiceReference1.DMLServiceClient dml = new ServiceReference1.DMLServiceClient();
                    dml.CreateFolder(target);
                    dmlcatalog.path = target;
                    dmlcatalog.locked = false;

                    db.dmlcatalog.Add(dmlcatalog);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult validationError in ex.EntityValidationErrors)
                    {
                        Response.Write("Object: " + validationError.Entry.Entity.ToString());
                        Response.Write(" ");
                        foreach (DbValidationError err in validationError.ValidationErrors)
                        {
                            Response.Write(err.ErrorMessage + " ");
                        }
                    }
                }


                
            }


            //выполнение в случае ошибки
            ViewBag.path = target;
            ViewBag.guid = Guid.NewGuid();
            ViewBag.localizeid = new SelectList(db.dmllocalize, "id", "name", dmlcatalog.localizeid);
            ViewBag.publisherid = new SelectList(db.dmlpublisher, "id", "name", dmlcatalog.publisherid);
            ViewBag.stateid = new SelectList(db.dmlstate, "id", "name", dmlcatalog.stateid);
            ViewBag.typeid = new SelectList(db.dmltype, "id", "name", dmlcatalog.typeid);
            return View(dmlcatalog);
        }

        // GET: dmlcatalogs/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlcatalog dmlcatalog = db.dmlcatalog.Find(id);
            if (dmlcatalog == null)
            {
                return HttpNotFound();
            }
            TempData["state"] = dmlcatalog;

            ViewBag.localizeid = new SelectList(db.dmllocalize, "id", "name", dmlcatalog.localizeid);
            ViewBag.publisherid = new SelectList(db.dmlpublisher, "id", "name", dmlcatalog.publisherid);
            ViewBag.stateid = new SelectList(db.dmlstate, "id", "name", dmlcatalog.stateid);
            ViewBag.typeid = new SelectList(db.dmltype, "id", "code", dmlcatalog.typeid);

            
            

            return View(dmlcatalog);
        }

        // POST: dmlcatalogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,guid,version,description,stateid,typeid,publisherid,localizeid,path,locked")] dmlcatalog dmlcatalog)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            //считать текущие значения
            Dictionary<int,string> st = new Dictionary<int,string>();
            st.Add(0,dmlcatalog.name);
            st.Add(1,dmlcatalog.version);
            st.Add(2,dmlcatalog.description);
            st.Add(3,dmlcatalog.stateid.ToString());
            st.Add(4,dmlcatalog.typeid.ToString());
            st.Add(5,dmlcatalog.publisherid.ToString());
            st.Add(6,dmlcatalog.localizeid.ToString());
            st.Add(7, dmlcatalog.locked.ToString());
            var state = TempData["state"] as dmlcatalog;
            Dictionary<int, string> st1 = new Dictionary<int, string>();
            st1.Add(0,state.name);
            st1.Add(1,state.version);
            st1.Add(2,state.description);
            st1.Add(3,state.stateid.ToString());
            st1.Add(4,state.typeid.ToString());
            st1.Add(5,state.publisherid.ToString());
            st1.Add(6,state.localizeid.ToString());
            st1.Add(7,state.locked.ToString());
            var list3 = st.Except(st1).ToList();
            List<string> param = new List<string>();
            param.Add("name");
            param.Add("version");
            param.Add("description");

DMLCatalog/DMLCatalog/Views/dmlcatalogs/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Create.cshtml
@model DMLCatalog.Models.dmlcatalog

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>
@ViewBag.error


    @using (Html.BeginForm("Create", "dmlcatalogs", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>dmlcatalog</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })


            <div class="form-group">
                @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
                </div>
            </div>
            @{string name = "Имя";
                string version = "Версия";
                string desc = "Описание";
            }
            <div class="form-group">
                @Html.Label(name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>


            <div class="form-group">
                @Html.LabelFor(model => model.guid, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">

                    @Html.EditorFor(model => model.guid, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                    @Html.ValidationMessageFor(model => model.guid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label(version, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.version, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.version, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.Label(desc, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">


                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.stateid, "Состояние", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("stateid", null, "Выберите...", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.stateid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.typeid, "Тип", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("typeid", null, "Выберите...", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.typeid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.publisherid, "Разработчик", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("publisherid", null, "Выберите...", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.publisherid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.localizeid, "Язык", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("localizeid", null, "Выберите...", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.localizeid, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

        </div>
    }



    <div>
        @Html.ActionLink("Загрузить информацию из файла", "Upload")
    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Delete.cshtml
@model DMLCatalog.Models.dmlcatalog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>dmlcatalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.guid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.guid)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.version)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dmllocalize.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmllocalize.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dmlpublisher.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmlpublisher.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dmlstate.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmlstate.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dmltype.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmltype.code)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Details.cshtml
@model DMLCatalog.Models.dmlcatalog

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>dmlcatalog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayName("Имя")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.guid)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.guid)
        </dd>

        <dt>
            @Html.DisplayName("Версия")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.version)
        </dd>

        <dt>
            @Html.DisplayName("Описание")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayName("Язык")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmllocalize.name)
        </dd>

        <dt>
            @Html.DisplayName("Разработчик")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmlpublisher.name)
        </dd>

        <dt>
            @Html.DisplayName("Состояние")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmlstate.name)
        </dd>

        <dt>
            @Html.DisplayName("Тип")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dmltype.code)
        </dd>

        <dt>
            @Html.DisplayName("Путь")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.path)
        </dd>

        <dt>
            @Html.DisplayName("Только чтение")
        </dt>

        <dd>
            @Html.DisplayFor(model => model.locked)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Edit.cshtml
@model DMLCatalog.Models.dmlcatalog

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>dmlcatalog</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id)

    <div class="form-group">
        @Html.Label("Имя", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.guid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.guid, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.guid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Версия", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.version, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.version, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.Label("Описание", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.stateid, "Состояние", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("stateid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.stateid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.typeid, "Тип", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("typeid", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.typeid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.publisherid, "Разработчик", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("publisherid", null, "Выберите", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.publisherid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.localizeid, "Язык", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("localizeid", null, "Выберите", htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.localizeid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.path, "Путь", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.path, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.path, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
       
        @Html.LabelFor(model => model.locked, "Только чтение", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @if (Model.locked != true)
            {@Html.CheckBoxFor(model => model.locked, new { htmlAttributes = new { @class = "form-control" } });}
            else
            {@Html.CheckBoxFor(model => model.locked, new { onclick = "return false" });}
            @Html.ValidationMessageFor(model => model.locked, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}



<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Index.cshtml
@model IEnumerable<DMLCatalog.Models.dmlcatalog>

@{
    ViewBag.Title = "Index";
}

<h2>Список ПО</h2>

@if (ViewBag.groups.Contains("DMLAdmins") || ViewBag.groups.Contains("DMLTesters"))
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
    <table class="table">
        <tr>
            <th>
                @Html.DisplayName("Имя")
            </th>
            @if (ViewBag.groups.Contains("DMLAdmins"))
            {
                <th>
                    @Html.DisplayNameFor(model => model.guid)
                </th>
            }
            <th>
                @Html.DisplayName("Версия")
            </th>
            <th>
                @Html.DisplayName("Описание")
            </th>
            <th>
                @Html.DisplayName("Язык")
            </th>
            <th>
                @Html.DisplayName("Разработчик")
            </th>
            @if (ViewBag.groups.Contains("DMLAdmins"))
            {
                <th>
                    @Html.DisplayName("Состояние")
                </th>
            }
            <th>
                @Html.DisplayName("Тип приложения")
            </th>
            <th>
                @Html.DisplayName("Путь")
            </th>
            <th>
                @Html.DisplayName("Только чтение")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.name)
                </td>
                @if (ViewBag.groups.Contains("DMLAdmins"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.guid)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.version)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dmllocalize.name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.dmlpublisher.name)
                </td>
                @if (ViewBag.groups.Contains("DMLAdmins"))
                {
                    <td>
                        @Html.DisplayFor(modelItem => item.dmlstate.name)
                    </td>
                }
                <td>
                    @Html.DisplayFor(modelItem => item.dmltype.name)
                </td>
                @{string path = item.path;
                    string npath = "";
                }

                @foreach (char s in path)

                {
                    if (s == '\\')
                    { npath += "/"; }
                    else
                    {
                        npath += s;
                    }
                }
                @{npath = "file:" + npath;}

                <td>
                    <a onclick="run('@npath')">@Html.DisplayFor(modelItem => item.path)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.locked)
                </td>
                <td>
                    @if (ViewBag.groups.Contains("DMLAdmins"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.id })}|
                    @Html.ActionLink("Details", "Details", new { id = item.id }) @*|
                        @Html.ActionLink("Delete", "Delete", new { id = item.id })*@
                </td>
            </tr>
        }

    </table>

    <script>
        function run(command) {
            //window.open(command);
            var myshell = new ActiveXObject("WScript.shell");
            myshell.run(command);
        }
    </script>

DMLCatalog/DMLCatalog/Views/dmlcatalogs/Upload.cshtml
@{
    ViewBag.Title = "Upload";
}
<h3>Выберите файл для загрузки</h3>
@using (Html.BeginForm("Upload", "dmlcatalogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <input type="file" name="upload" /><br>
    <input type="submit" value="Загрузить" />
}