DMLCatalog/DMLCatalog/Controllers/dmlhistoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DMLCatalog.Models;

namespace DMLCatalog.Controllers
{
    public class dmlhistoriesController : Controller
    {
        private dmldbEntities db = new dmldbEntities();

        // GET: dmlhistories
        public ActionResult Index()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            var dmlhistory = db.dmlhistory.Include(d => d.dmlcatalog);
            return View(dmlhistory.ToList());
        }

        public List<string> GetGroupNames(string domainName, string userName)
        {
            List<string> result = new List<string>();

            using (PrincipalContext principalContext = new PrincipalContext(ContextType.Domain, domainName))
            {
                using (PrincipalSearchResult<Principal> src = UserPrincipal.FindByIdentity(principalContext, userName).GetGroups())
                {
                    src.ToList().ForEach(sr => result.Add(sr.SamAccountName));
                }
            }

            return result;
        }

        // GET: dmlhistories/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlhistory dmlhistory = db.dmlhistory.Find(id);
            if (dmlhistory == null)
            {
                return HttpNotFound();
            }
            return View(dmlhistory);
        }

        // GET: dmlhistories/Create
        public ActionResult Create()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            ViewBag.catalogid = new SelectList(db.dmlcatalog, "id", "name");
            return View();
        }

        // POST: dmlhistories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,catalogid,datetime,owner,eventtext,paramname,paramold,paramnew")] dmlhistory dmlhistory)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                db.dmlhistory.Add(dmlhistory);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.catalogid = new SelectList(db.dmlcatalog, "id", "name", dmlhistory.catalogid);
            return View(dmlhistory);
        }

        // GET: dmlhistories/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlhistory dmlhistory = db.dmlhistory.Find(id);
            if (dmlhistory == null)
            {
                return HttpNotFound();
            }
            ViewBag.catalogid = new SelectList(db.dmlcatalog, "id", "name", dmlhistory.catalogid);
            return View(dmlhistory);
        }

        // POST: dmlhistories/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,catalogid,datetime,owner,eventtext,paramname,paramold,paramnew")] dmlhistory dmlhistory)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                db.Entry(dmlhistory).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.catalogid = new SelectList(db.dmlcatalog, "id", "name", dmlhistory.catalogid);
            return View(dmlhistory);
        }

        // GET: dmlhistories/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlhistory dmlhistory = db.dmlhistory.Find(id);
            if (dmlhistory == null)
            {
                return HttpNotFound();
            }
            return View(dmlhistory);
        }

        // POST: dmlhistories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmlhistory dmlhistory = db.dmlhistory.Find(id);
            db.dmlhistory.Remove(dmlhistory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMLCatalog/DMLCatalog/Controllers/dmlstatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DMLCatalog.Models;

namespace DMLCatalog.Controllers
{
    public class dmlstatesController : Controller
    {
        private dmldbEntities db = new dmldbEntities();

        // GET: dmlstates
        public ActionResult Index()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            return View(db.dmlstate.ToList());
        }

        public List<string> GetGroupNames(string domainName, string userName)
        {
            List<string> result = new List<string>();

            using (PrincipalContext principalContext = new PrincipalContext(ContextType.Domain, domainName))
            {
                using (PrincipalSearchResult<Principal> src = UserPrincipal.FindByIdentity(principalContext, userName).GetGroups())
                {
                    src.ToList().ForEach(sr => result.Add(sr.SamAccountName));
                }
            }

            return result;
        }

        // GET: dmlstates/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlstate dmlstate = db.dmlstate.Find(id);
            if (dmlstate == null)
            {
                return HttpNotFound();
            }
            return View(dmlstate);
        }

        // GET: dmlstates/Create
        public ActionResult Create()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmlstate dm = new dmlstate();
            var id =
                        (from c in db.dmlstate
                         select c.id).ToArray().LastOrDefault();
            dm.id = id + 1;
            return View(dm);
        }

        // POST: dmlstates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,description")] dmlstate dmlstate)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                try { 
                db.dmlstate.Add(dmlstate);
                db.SaveChanges();
                return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult validationError in ex.EntityValidationErrors)
                    {
                        Response.Write("Object: " + validationError.Entry.Entity.ToString());
                        Response.Write(" ");
                        foreach (DbValidationError err in validationError.ValidationErrors)
                        {
                            Response.Write(err.ErrorMessage + " ");
                        }
                    }
                }
            }

            return View(dmlstate);
        }

        // GET: dmlstates/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlstate dmlstate = db.dmlstate.Find(id);
            if (dmlstate == null)
            {
                return HttpNotFound();
            }
            return View(dmlstate);
        }

        // POST: dmlstates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,description")] dmlstate dmlstate)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                db.Entry(dmlstate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dmlstate);
        }

        // GET: dmlstates/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmlstate dmlstate = db.dmlstate.Find(id);
            if (dmlstate == null)
            {
                return HttpNotFound();
            }
            return View(dmlstate);
        }

        // POST: dmlstates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmlstate dmlstate = db.dmlstate.Find(id);
            db.dmlstate.Remove(dmlstate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMLCatalog/DMLCatalog/Controllers/dmltypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DMLCatalog.Models;

namespace DMLCatalog.Controllers
{
    public class dmltypesController : Controller
    {
        private dmldbEntities db = new dmldbEntities();

        // GET: dmltypes
        public ActionResult Index()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            return View(db.dmltype.ToList());
        }

        public List<string> GetGroupNames(string domainName, string userName)
        {
            List<string> result = new List<string>();

            using (PrincipalContext principalContext = new PrincipalContext(ContextType.Domain, domainName))
            {
                using (PrincipalSearchResult<Principal> src = UserPrincipal.FindByIdentity(principalContext, userName).GetGroups())
                {
                    src.ToList().ForEach(sr => result.Add(sr.SamAccountName));
                }
            }

            return result;
        }

        // GET: dmltypes/Details/5
        public ActionResult Details(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmltype dmltype = db.dmltype.Find(id);
            if (dmltype == null)
            {
                return HttpNotFound();
            }
            return View(dmltype);
        }

        // GET: dmltypes/Create
        public ActionResult Create()
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmltype dm = new dmltype();
            var id =
                        (from c in db.dmltype
                         select c.id).ToArray().LastOrDefault();
            dm.id = id + 1;
            return View(dm);
        }

        // POST: dmltypes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,name,description")] dmltype dmltype)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                try { 
                db.dmltype.Add(dmltype);
                db.SaveChanges();
                return RedirectToAction("Index");
                }
                catch (DbEntityValidationException ex)
                {
                    foreach (DbEntityValidationResult validationError in ex.EntityValidationErrors)
                    {
                        Response.Write("Object: " + validationError.Entry.Entity.ToString());
                        Response.Write(" ");
                        foreach (DbValidationError err in validationError.ValidationErrors)
                        {
                            Response.Write(err.ErrorMessage + " ");
                        }
                    }
                }
            }

            return View(dmltype);
        }

        // GET: dmltypes/Edit/5
        public ActionResult Edit(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmltype dmltype = db.dmltype.Find(id);
            if (dmltype == null)
            {
                return HttpNotFound();
            }
            return View(dmltype);
        }

        // POST: dmltypes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,name,description")] dmltype dmltype)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (ModelState.IsValid)
            {
                db.Entry(dmltype).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dmltype);
        }

        // GET: dmltypes/Delete/5
        public ActionResult Delete(int? id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            dmltype dmltype = db.dmltype.Find(id);
            if (dmltype == null)
            {
                return HttpNotFound();
            }
            return View(dmltype);
        }

        // POST: dmltypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ViewBag.groups = GetGroupNames("atbmarket", User.Identity.Name);
            dmltype dmltype = db.dmltype.Find(id);
            db.dmltype.Remove(dmltype);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DMLCatalog/DMLCatalog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</head>
<body style="padding-top:15px">
    <div class="container-fluid">
        <p style="text-align:right">Здравствуйте, @User.Identity.Name!</p>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            @Html.ActionLink("Definition Media Library", "Index", "dmlcatalogs", new { id = 0 }, new { @class = "navbar-brand" })
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        @Html.ActionLink("Домашняя страница", "Index", "dmlcatalogs", new { id = 0 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Приложения", "Index", "dmlcatalogs", new { id = 1 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Драйвера", "Index", "dmlcatalogs", new { id = 2 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("ОС", "Index", "dmlcatalogs", new { id = 3 }, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Скрипты", "Index", "dmlcatalogs", new { id = 4 }, new { @class = "nav-link" })
                    </li>
                </ul>

                <form class="form-inline my-2 my-lg-0" method="get" action="@Url.Action("Search", "dmlcatalogs")">
                    <input class="form-control mr-sm-2" type="text" placeholder="Search" name="search" id="search">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>
    </div>
    <div class="container-fluid">
        <div class="row">

                @if (ViewBag.groups.Contains("DMLAdmins"))
                            {
                                <aside class="col-md-1">
                                    <ul class="list-group submenu">
                                        <li class="list-group-item">
                                            @Html.ActionLink("Список ПО", "Index", "dmlcatalogs")
                                        </li>
                                        <li class="list-group-item">
                                            @Html.ActionLink("История изменений", "Index", "dmlhistories")
                                        </li>
                                        <li class="list-group-item">
                                            @Html.ActionLink("Список локализаций", "Index", "dmllocalizes")
                                        </li>
                                        <li class="list-group-item">
                                            @Html.ActionLink("Список разработчиков", "Index", "dmlpublishers")
                                        </li>
                                        <li class="list-group-item">
                                            @Html.ActionLink("Список состояний", "Index", "dmlstates")
                                        </li>
                                        <li class="list-group-item">@Html.ActionLink("Список типов ПО", "Index", "dmltypes")</li>
                                    </ul>
                                </aside>
                            }
                            <section class="col-md-11" style="padding-top:15px">

                                @RenderBody()
                                <hr />
                                <footer>
                                    <p>&copy; @DateTime.Now.Year – DML-каталог <a href="mailto:dml@gmail.com">dml@gmail.com</a></p>
                                </footer>

                            </section>
        </div>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("Scripts", required: false)
</body>
</html>